-- A script that creates a database 'hbtn_0d_usa' and a table 'states'
--  with a unique autogenerated primary key `id`
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states(
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(256) NOT NULL,
    UNIQUE(`id`),
    PRIMARY KEY(`id`)
);
